exports.UserList = [
  {
    id: 1,
    name: "kee",
    email: "kee@gmail.com",
    address: "bangalore",
    gender: "female",
    age: 50,
  },
  {
    id: 2,
    name: "keerthi",
    email: "keerthi@gmail.com",
    address: "bangalore",
    gender: "male",
    age: 70,
  },
  {
    id: 3,
    name: "Chan",
    email: "chan@gmail.com",
    address: "bangalore",
    gender: "female",
    age: 34,
  },
  {
    id: 4,
    name: "hiral",
    email: "hiral@gmail.com",
    address: "mangalore",
    gender: "male",
    age: 20,
  },
  {
    id: 5,
    name: "swathi",
    email: "swathi@gmail.com",
    address: "AP",
    gender: "female",
    age: 29,
  },
  {
    id: 6,
    name: "dhanu",
    email: "dhanu@gmail.com",
    address: "mangalore",
    gender: "female",
    age: 30,
  },
  {
    id: 7,
    name: "bhanu",
    email: "bhanu@gmail.com",
    address: "mangalore",
    gender: "female",
    age: 78,
  },
];
